media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string, default: "Nate Barksdale" }
      - { name: pubDatetime, label: Pub Date, type: date }
      - { name: modDatetime, label: Mod Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: OG Image Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: description, label: Description, type: string }
      - { name: emoji, label: Emoji, type: string, default: "✨" }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
